# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import atuador_pb2 as atuador__pb2


class atuadorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendInfo = channel.unary_unary(
                '/atuadorService/sendInfo',
                request_serializer=atuador__pb2.command.SerializeToString,
                response_deserializer=atuador__pb2.status.FromString,
                )


class atuadorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_atuadorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.sendInfo,
                    request_deserializer=atuador__pb2.command.FromString,
                    response_serializer=atuador__pb2.status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atuadorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class atuadorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/atuadorService/sendInfo',
            atuador__pb2.command.SerializeToString,
            atuador__pb2.status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
